version: '3.7'
services:
  wordpress:
    image: visiblevc/wordpress:0.21.0-php7.2
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse
    environment:
      DB_PASS: root
      DB_USER: root
      PLUGINS: >-
        query-monitor
    ports:
      - 8080:80
    volumes:
      - ./simple-job-board:/app/wp-content/plugins/simple-job-board
  db:
    image: mariadb:10
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 22222:80
    volumes:
      - data:/var/lib/mysql

volumes:
  ? data
